AVAILABLE_SKILLS = [
    "Python", "JavaScript", "TypeScript", "Java", "C#", "C++", "Go", "Rust", "Swift", "Kotlin", "PHP", "Ruby", "Perl", "Scala",
    "HTML", "CSS", "Sass", "Less", "Tailwind CSS", "Bootstrap",
    "React", "Vue", "Angular", "Svelte", "Next.js", "Nuxt.js", "Gatsby", "Redux", "MobX", "Vuex",
    "Node.js", "Express", "Django", "Flask", "FastAPI", "Spring Boot", "Ruby on Rails", "ASP.NET", "Laravel",
    "SQL", "PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "Cassandra", "Kafka", "RabbitMQ",
    "Linux", "Windows Server", "Docker", "Kubernetes", "OpenShift", "Terraform", "Ansible", "Puppet", "Chef",
    "CI/CD", "Jenkins", "GitLab CI", "GitHub Actions", "Travis CI", "Argo CD",
    "AWS", "Azure", "GCP", "Heroku", "Netlify", "Vercel",
    "Machine Learning", "Deep Learning", "Data Science", "Computer Vision", "NLP", "Reinforcement Learning",
    "Pandas", "NumPy", "Scikit-learn", "TensorFlow", "PyTorch", "Keras", "OpenCV", "NLTK", "SpaCy",
    "Algorithms", "Data Structures", "System Design", "Networking", "Security", "Cryptography", "Blockchain",
    "Mathematics", "Linear Algebra", "Calculus", "Statistics", "Probability", "Discrete Mathematics",
    "Git", "SVN", "Mercurial", "Agile", "Scrum", "Kanban", "Project Management", "Product Management", "Jira", "Confluence",
    "A/B Testing", "Analytics", "Business Intelligence", "Data Visualization", "Tableau", "Power BI",
    "iOS", "Android", "React Native", "Flutter", "Xamarin", "SwiftUI", "Jetpack Compose", "Xcode", "Android SDK",
    "Unity", "Unreal Engine", "Game Design", "WebGL", "OpenGL", "DirectX",
    "UX/UI Design", "Figma", "Adobe XD", "Sketch", "InVision", "User Research", "Wireframing", "Prototyping",
    "Backend", "Frontend", "Full Stack", "DevOps", "QA", "Testing", "Automation Testing", "Manual Testing",
    "REST API", "GraphQL", "gRPC", "Microservices", "Serverless", "Event-Driven Architecture",
    "Indexing", "Optimization", "Performance Tuning", "Scalability", "High Availability", "Load Balancing",
    "IT", "AI", "Digital", "Computer Science", "Design", "Engineering", "Programming", "Cybersecurity",
    "Digital Marketing", "Software Engineering", "Robotics", "Biotechnology", "Genetics", "Chemistry", "Physics",
    "Software Development", "Economics", "Finance", "Business Analytics", "Marketing Analytics",
    "IT Management", "Management", "Public Policy", "Digital Transformation", "Change Management",
    "Telecommunications", "Electronics", "Marine Technology", "Aerospace Engineering", "Automotive",
    "Cloud Computing", "Big Data", "Data Warehousing", "ETL", "Business Analysis", "Technical Writing",
    "Communication", "Teamwork", "Leadership", "Problem Solving", "Critical Thinking", "Creativity",
    "Time Management", "Adaptability", "Negotiation", "Presentation Skills", "Public Speaking"
]

